ioBroker/ioBroker.repositories

.gitignore
sources-dist-stable.json

publish stable version from landroid

publish stable version from landroid

---

sources-dist-stable.json
sources-dist.json

Version incremented: lightify, tr-064, wifilight, yamaha
Added firetv tosource-dist.json

Some new version  numbers

---

sources-dist-stable.json

Updated the version for the innogy-smarthome (important update!)

Updated innogy-smarthome

---

sources-dist-stable.json

(ldittmar) wrong type

---

sources-dist-stable.json

* update fronius to 1.0.0
* update landroid to 1.0.0

(ldittmar) Update fronius and landroid

---

sources-dist.json

Test-Thread: http://forum.iobroker.net/viewtopic.php?f=36&t=6311
AppVeyor has problems downloading node-gyp sources atm, so the build status might be failing:
https://appveyor.statuspage.io/incidents/2tjbzx1mtnz8

Add IKEA Tradfri adapter

---

sources-dist.json

Test-Thread: http://forum.iobroker.net/viewtopic.php?f=36&t=7546
AppVeyor has problems downloading node-gyp sources atm, so the build status might be failing:
https://appveyor.statuspage.io/incidents/2tjbzx1mtnz8

Add g-homa adapter

---

sources-dist.json

Correct the link to io-package.json for tradfri

---

sources-dist.json

New adapters, not yet ready for "stable", but good enough to be taken into ioBroker.

I2C and KeContact adapters

---

sources-dist.json

Test thread: http://forum.iobroker.net/viewtopic.php?f=36&t=7932
GitHub: https://github.com/AlCalzone/ioBroker.ble
CI tests are running, I successfully tested on RasPi 3. Not sure where else it works.

add BLE adapter

---

sources-dist-stable.json

I think the current version is good enough for the stable repo.

Add Tradfri to stable

---

sources-dist-stable.json

Fronius 1.0.2 tested and ready for stable

(ldittmar) Fronius 1.0.2 -> stable

---

sources-dist-stable.json

After a few bugfix and tests on different os and node systems, i think the adapter is now ready for stable.

Landroid-S is stable

---

sources-dist-stable.json
sources-dist.json

Added bmw and broadlink2-Adapters and changed names where adapters have been renamed to ioBroker

Updated laRenamed and added adapterstest adapters renamed

---

sources-dist-stable.json

Panasonic Adapter works fine and is stable.

(ldittmar) panasonic adapter stable

---

sources-dist-stable.json

Updated amazon-dash

---

sources-dist-stable.json

The haier adapter is an air conditioning adapter

(ldittmar) change type of haier

---

sources-dist.json

Mihome-lamp type to lighting - ist not in stable

(ldittmar)  change mihome-lamp type

---

sources-dist-stable.json
sources-dist.json

Change type of tradfri and g-homa

---

sources-dist.json

Hab es in der richtigen Reihenfolge rein gemacht und den meta korrigiert - vorher: master/package.json

(ldittmar) fix viessmann-tcp

---

sources-dist-stable.json
sources-dist.json

Habe eine Böse Mail von worx bekommen, dass ich es auf der Stelle zu löschen habe...

Muss gelöscht werden

---

sources-dist.json

Hope, that everything is set up correctly.
Testing is successfully set up up and running on Travis-CI, but not for Appveyor.

added bosesoundtouch adapter to sources-dist.json (latest)

---

sources-dist-stable.json

opi monitor implemented

---

sources-dist-stable.json

As discussed here
https://github.com/ioBroker/ioBroker.zwave/issues/33

Bump zwave

---

sources-dist.json

Hi. Aufgrund der Vielzahl der Geo-Adapter (OwnTracks, Geofency, EgiGeoZone) und deren redundantes "Home"-Handling: hier mal eine generische Variante mit der Möglichkeit, beliebig viele Orte erstellen und rein message-basiert arbeiten zu können. VG Bastian

added places adapter

---

sources-dist-stable.json

Like talked to @Apollon77 in the afternoon, here's the PR.

changed telegram version, added places adapter

---

sources-dist-stable.json
sources-dist.json

0.5.3 version was not open port with updated version serialport (was wrong parameter name)

Zigbee quick fix version

---

sources-dist-stable.json

VR200 stable version

---

sources-dist-stable.json
sources-dist.json

Added nanoleaf-lightpanels adapter in latest and Version 0.4.1 to stable.
Adapter was tested in commmunity [https://forum.iobroker.net/viewtopic.php?f=20&t=13692](url)

nanoleaf-lightpanels adapter

---

sources-dist-stable.json

https://forum.iobroker.net/viewtopic.php?f=36&t=15277 + Denon stable updates

Stable updates according to apollons thread

---

sources-dist.json

added alpha2 adapter

---

sources-dist.json

SIA Adapter for alarm systems like Lupusec, ABUS, ...

SIA Adapter for alarm systems

---

sources-dist-stable.json
sources-dist.json

https://forum.iobroker.net/viewtopic.php?f=24&t=15628

added energymanager

---

sources-dist.json

I added my first adapter for the wiffi-wz, i hope everything is fine.

added adapter for wiffi-wz

---

sources-dist-stable.json

support for more kiwigrid-powered devices

new version for energymanager

---

sources-dist-stable.json
sources-dist.json

-added sonnen to latest repo
-added sonnen to stable repo

added sonnen adapter

---

sources-dist-stable.json

all features implemented successfully

confirmed stable release of energymanager

---

sources-dist-stable.json

- Denon stable update from 0.2.2 to 0.3.5

Updated Denon stable to 0.3.5

---

sources-dist-stable.json

Add Lupusec Adapter to stable Version

---

sources-dist-stable.json

added sonnen stable

---

sources-dist-stable.json

DENON stable 3.5 --> 3.6

---

sources-dist-stable.json
sources-dist.json

initial and confirmed stable relase of the stiebel-isg adapter for stiebel-eltron/tecalor internet service gateway. (heatpumps)
forum-thread:
https://forum.iobroker.net/viewtopic.php?f=24&t=14309

initial confirmed stable release of stiebel-isg

---

sources-dist-stable.json

Add klf200 to stable repository

Add klf200 to stable repository

---

sources-dist-stable.json
sources-dist.json

this version seems to be stable according to the feedback in the forum

added wiffi to stable repo and updated recent to recent version of wiffi

---

sources-dist.json

- Add Xbox adapter
- tested in https://forum.iobroker.net/viewtopic.php?f=36&t=17044&p=178951#p178951
- bluefox added as npm owner

Add Xbox to latest

---

sources-dist-stable.json

- version bump for DENON 0.3.6 --> 0.4.4

DENON/Marantz stable 0.4.4

---

sources-dist-stable.json

-closes https://github.com/arteck/ioBroker.hs100/issues/34

add hs100 to stable

---

sources-dist-stable.json

-just a formal increment due to satisfy semaVer
-no change to old stable versions

update version number of denon/sonnen

---

sources-dist-stable.json

https://forum.iobroker.net/viewtopic.php?f=24&t=2754&p=188411

ioBroker.feiertage now 1.0.11

---

sources-dist-stable.json
sources-dist.json

- Updated latest stable version of innogy smarthome adapter (required by the INNOGY/RWE team)

Updated innogy adapter to the latest version

---

sources-dist.json

Asterisk Adapter

---

sources-dist-stable.json

Stable version for Shelly, ConntactID und SIA Adapter

SIA, ConntactID and Shelly

---

sources-dist-stable.json

Push g-homa 0.4.0 to stable

---

sources-dist-stable.json

-making minor fix available for stable

denon minor update

---

sources-dist.json

https://github.com/DutchmanNL/ioBroker.discovergy

adding adapter Discovergy

---

sources-dist-stable.json

Solarlog: new version 0.0.6

---

sources-dist.json

Opentherm adapter allows to read data from opentherm gateway (heating).
currently in beta state and testing at 3 installations, in latre releases control of several values will also be possible

add opentherm adapter to latest

---

sources-dist-stable.json

Tested in the forum (e.g. https://forum.iobroker.net/viewtopic.php?f=35&t=12835#p191254) and issues on Github (https://github.com/Zefau/ioBroker.nello/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed).

Add nello adapter to stable

---

sources-dist-stable.json

- Add Asterisk Adapter, 
- New version for Lupusec Adapter

Add Asterisk Adapter, new version for Lupusec Adapter

---

sources-dist-stable.json
sources-dist.json

Updated latest stable version of innogy smarthome adapter (required by the INNOGY/RWE team)

Innogy Adapter update

---

sources-dist-stable.json

+ hm-rpc and hm-rega
+ sonnen, denon (just changed to adapter-core)
+ xbox adapter added --> will try to add discovery as soon as in official repo

add xbox to stable + other upgrades

---

sources-dist-stable.json
sources-dist.json

Reverted changes from yesterday, as RW states are not correctly maintained by innogy

Reverted changes

---

sources-dist-stable.json

Solarlog V008

---

sources-dist-stable.json

- Denon 1.2.2 => 1.2.7
- hm-rpc 1.8.0 => 1.8.2

update denon and hm-rpc stable

---

sources-dist-stable.json
sources-dist.json

Test Problems solved, thx for the help. Tests are green and no Warnings.
If something is missing which i did not notice please feel free to notice me.
thx

Add ASUSWRT 0.3.1

---

sources-dist-stable.json

DENON, Xbox, sonnen, amazon-dash and harmony

Stable upgrades

---

sources-dist-stable.json

As requested in https://github.com/UncleSamSwiss/ioBroker.kecontact/issues/9

Added ioBroker.kecontact 0.1.0

---

sources-dist.json

ioBroker SourceAnalytix allows you to keep track & trace power consumption for your devices. You need data as input (total amount of Wh used) from your devices and this adapter will :
Trace power usage daily, weekly, monthly, quarterly, yearly
calculate costs (current price is configurable)
Can be used for Power Consumption and GAS
Input values can be wh/kWh/m3

add SourceAnalytix

---

sources-dist-stable.json
sources-dist.json

* add discovergy to stable repro
* correct icon for SourceAnalytix

add discovergy to stable repro

---

sources-dist-stable.json
sources-dist.json

forum-thread:
https://forum.iobroker.net/viewtopic.php?f=36&p=220258

added snips-adapter

---

sources-dist-stable.json

fronius, landroid, panasonic, sony

Update Versions (fronius, landroid, panasonic, sony)

---

sources-dist-stable.json
sources-dist.json

landroid, panasonic-viera and sony-bravia

Move to iobroker-community-adapters

---

sources-dist-stable.json

Updated enet, hp-ilo, lgtv and lgtv11 cause of implementation of compat mode.

 Updated enet, hp-ilo, lgtv and lgtv11

---

sources-dist.json

Nuki adapter changed to version 1.0.4 in latest repository bacause of added support for compact mode.

Nuki adapter: added Support for Compact mode

---

sources-dist-stable.json

**Change version in stable:**
- asterisk
- contactid
- lupusec
- shelly
- sia
**New adapter in stable:**
- ring
Version date deleted, only publish date supported. I hope that is correct.

new version: asterisk, contactid, lupusec, ring, shelly, sia in stable

---

sources-dist-stable.json
sources-dist.json

new confirmed stable version for following adapters
- energymanager
- snips
- stiebel-isg

new confirmed stable version

---

sources-dist-stable.json
sources-dist.json

new stable version for stiebel-isg

---

sources-dist.json

adding oppoplayer adapter to latest repro

add oppoplayer to latest repro

---

sources-dist-stable.json
sources-dist.json

First published version. Ready on github & npm, tested by TheDuke

Smappee V0.0.3

---

sources-dist-stable.json
sources-dist.json

Smappee V004 to sources-dist

---

sources-dist-stable.json

New Version of following adapter
- ring
- shelly
- lupusec

New version of ring, shelly, lupusec adapter

---

sources-dist-stable.json
sources-dist.json

new stable version for snips

---

sources-dist.json

Added entry for https://github.com/thovid/ioBroker.viessmannapi to latest.

Added viessmannapi adapter to latest

---

sources-dist-stable.json

Smappee V010 stable

---

sources-dist.json

Adapter for Bring! shopping lists

added bring to latest

---

sources-dist-stable.json

Stable update

---

sources-dist.json

First published version. Travis-CI and adapter-checker approved.

V0.0.2 Comfoair

---

sources-dist-stable.json

Tested by TheDuke.
Appveyor test OK
Travis test for ioBroker 1.5.x OK

Smappee V 0.2.0

---

sources-dist-stable.json
sources-dist.json

virtualpowermeter add

---

sources-dist-stable.json

Add Pollenflug  adapter to stable

add Pollenflug adapter to stable

---

sources-dist-stable.json

* ioBroker.admin
* ioBroker.flot
* ioBroker.history
* ioBroker.ical
* ioBroker.openhab
* ioBroker.rickshaw
* ioBroker.text2command
* ioBroker.vis
https://forum.iobroker.net/topic/20408/stable-repository-update-feedback/4

update latest to stable & correct release date of version

---

sources-dist-stable.json

It was tested by various users.

Add new radar2-adapter to stable.

---

sources-dist-stable.json

Please publish version as stable to publish the remark in the README that a parallel use of the adapter with the device' control panel is not recommended!

Major 'bugfix' Comfoair

---

sources-dist-stable.json
sources-dist.json

ioBroker-Forum: https://forum.iobroker.net/topic/18646/nibe-w%C3%A4rmepumpe

Nibeuplink adapter added

---

sources-dist-stable.json

Add Beckhoff Adapter to stable Repositiory

Add beckhoff to Stable

---

sources-dist-stable.json
sources-dist.json

Just to complete all steps for a successful transfer ;)

changed repository URL for places adapter

---

sources-dist.json

Signed-off-by: SchumyHao <schumyhaojl@126.com>

Add new adapter ioBroker.miio

---

sources-dist-stable.json

landroid-s update

---

sources-dist.json

please let me know if something is missing

add iobroker.valloxmv adapter

---

sources-dist.json

Adapter for monitoring and maintenance

New Adapter MoMa

---

sources-dist-stable.json

Forum: https://forum.iobroker.net/topic/20098/neuer-adapter-emby

Added Emby to stable

---

sources-dist-stable.json

new confirmed stable versions for two adapters

new stable versions for snips and stiebel-isg

---

sources-dist.json

https://www.forum.iobroker.net/topic/21377/aufruf-iobroker-gr%C3%BCnbeck-adapter

add gruenbeck adapter to latest

---

sources-dist.json

https://forum.iobroker.net/topic/22314/aufruf-mecedes-me-adapter

mercedes me adapter

---

sources-dist.json

adapter linkeddevices added

---

sources-dist.json

Forum-Thread for first testings:
https://forum.iobroker.net/topic/22715/aufruf-neuer-adapter-iobroker-pi-hole

new adapter pi-hole

---

sources-dist-stable.json

added vallox mv release
got some positive feedback already:
https://forum.iobroker.net/topic/21897/aufruf-valloxmv-adapter

ValloxMV going stable

---

sources-dist-stable.json

confirmed stabled version of pi-hole adapter, only rise of version number for stable repo

added pi-hole adapter

---

sources-dist-stable.json

Stable version for following adapters:
- Lupusec
- Ring
- Shelly
- SIA

Lupusec, Ring, Shelly, SIA

---

sources-dist.json

if adapter is stable, landroid-s will be removed

add worx adapter

---

sources-dist.json

https://github.com/dna909/ioBroker.homeconnect
https://forum.iobroker.net/topic/16446/aufruf-bsh-home-connect-adapter

Add homeconnect

---

sources-dist-stable.json

new stable version for following adapters:
- SIA (alarm system)
- Shelly 
- Lupusec (alarm system)

Stable Version SIA, Shelly, Lupusec

---

sources-dist-stable.json

https://forum.iobroker.net/topic/16446/aufruf-bsh-home-connect-adapter
https://forum.iobroker.net/topic/22314/aufruf-mecedes-me-adapter
https://www.forum.iobroker.net/topic/21377/aufruf-iobroker-grünbeck-adapter/

add homeconnect, gruenbeck, mercedesme to stable

---

sources-dist-stable.json

updated readme
remove states created from previous versions of the adapter

Update homeconnect version

---

sources-dist-stable.json
sources-dist.json

fixed an annoying bug in the current version

updated to stable wiffi-version 2.1.3

---

sources-dist-stable.json

- stable versions confirmed in forum

new stable versions for stiebel-isg and pi-hole

---

sources-dist-stable.json

bump Nuki2 to stable release (no changes)

---

sources-dist.json

new adapter letrika_comgw

---

sources-dist-stable.json

Shelly Adapter in version 3.0.8

Shelly Adapter Version 3.0.8

---

sources-dist.json

Lets see if SVG instead of PNG works, shall we?

Add ZWave2 to latest repo

---

sources-dist-stable.json

Improve error messages when service is unavailable

Update homeconnect adapter

---

sources-dist-stable.json

Update nina adapter

---

.eslintrc.json
README.md
gulpfile.js
lib/scripts.js
package.json

This adds a new command to get a new adapter into the latest repo:
```
gulp addToLatest --name <adapter-name> --type <adapter-type>
```
Fixes: #480 
/cc @GermanBluefox @Apollon77

Add scripts to add a new adapter to latest/stable

---

sources-dist-stable.json

z-wave stable version

---

lib/scripts.js

Require url package

---

sources-dist.json

- release vedirect
- npm package ready this evening
- testing OK
- JS 2.0 compatible

release vedirect & Tado to latest

---

sources-dist-stable.json

new confirmed stable-versions for energymanager and stiebel-isg

Update stable-versions for energymanager and stiebel-isg

---

sources-dist-stable.json

Reduce network traffic and small bugfixes

Update iogo to 0.4.17

---

sources-dist-stable.json

bump hue stable

---

sources-dist-stable.json

Update Tradfri to 2.4.4

---

sources-dist-stable.json

in preparation for JS-Controller 2.0 in stable

Update BLE version

---

sources-dist-stable.json

I tested it with my testing and production ioBroker. I also got an positive response from a user via email. Also here:
https://forum.iobroker.net/topic/26531/test-adapter-nibeuplink-v0-3-0-latest

Set version of nibeuplink to 0.3.0

---

sources-dist-stable.json

Linkeddevices v1.1.0 stable

---

sources-dist-stable.json

Added adapter **ds18b20** to stable.
Forum thread: https://forum.iobroker.net/topic/25610/test-adapter-ds18b20-v1-1-x

Add ds18b20 to stable

---

sources-dist-stable.json

Added adapter **odl** to stable.
Forum thread: https://forum.iobroker.net/topic/25979/test-adapter-odl-ortsdosisleistung-v1-0-x

Add odl to stable

---

sources-dist-stable.json

MoMa Release 1.2.3

---

sources-dist-stable.json

new stable version:
- Lupusec adapter: add new devices to the adapter
- Shelly adapter: add new devices like Shelly Plugs S2 to the adapter / auto firmware update

Stable Version Shelly and Lupusec adapter

---

sources-dist-stable.json

Testing is red because materializeCSS is not yet supported

Increase G-Homa stable version

---

sources-dist-stable.json

Feedback luxtronik: [https://forum.iobroker.net/topic/20185/adapter-luxtronik-1-w%C3%A4rmepumpensteuerung/43](https://forum.iobroker.net/topic/20185/adapter-luxtronik-1-w%C3%A4rmepumpensteuerung/43)
Feedback Solarlog: [https://github.com/iobroker-community-adapters/ioBroker.solarlog/issues/20#issuecomment-570945332](https://github.com/iobroker-community-adapters/ioBroker.solarlog/issues/20#issuecomment-570945332)

luxtronik 0.1.0 / solarlog 1.2.1 to stable

---

sources-dist-stable.json

bump some stable versions

---

sources-dist-stable.json

Version 0.9.2 is running stable since months

Update Yahka to 0.9.2

---

sources-dist-stable.json

ioBroker.valloxmv 1.0.3

---

sources-dist.json

Adapter for controlling Somfy Tahoma

Added somfy tahoma adapter

---

sources-dist.json

ioBroker.plenticore Adapter for KOSTAL Plenticore Plus

- added plenticore adapter

---

sources-dist-stable.json

see https://www.npmjs.com/package/iobroker.feiertage

Updated ioBroker.feiertage to 1.0.15

---

sources-dist.json

There is a thread on the forum, but it does not have any posts for a long time now...
Maybe if it is in latest, some people will find it and test.
For me it works fine since over a month now. 👍

add mydlink adadpter to latest

---

sources-dist.json

https://forum.iobroker.net/topic/28288/test-adapter-fb-checkpresence-v0-2-x

fb-checkpresence

---

sources-dist-stable.json

0.10.2 is very old and not more supported

zigbee 1.0.2

---

sources-dist.json

https://forum.iobroker.net/topic/29506/test-adapter-openligadb-v0-0-x

new adapter for openligadb soccer sport data

---

sources-dist.json

Added MieleCloudService (formerly known as MieleAtHome) to get it into the repo.

Added MieleCloudService

---

sources-dist-stable.json
sources-dist.json

Move roomba to iobroker-community-adapters

---

sources-dist-stable.json

add nuki-extended to stable and furthermore add nuki2 to stable with v1.0.5 for deprecation notice (will be removed in one month)

add nuki-extended to stable

---

sources-dist.json

See https://forum.iobroker.net/topic/27050/test-adapter-trashschedule-v0-0-x/ for details

Added Trashschedule adapter

---

sources-dist.json

Please add senec adapter to latest. It is ready for feedback and testing.

Add senec adapter to latest

---

sources-dist-stable.json

please add first stable version of heatingcontrol 0.3.17

first stable version of heatingcontrol 0.3.17

---

sources-dist.json

Please add beta version of noolitef adapter
Thanks

Add noolitef adapter to repository

---

sources-dist-stable.json

feedback see: [Forum:Tester](https://forum.iobroker.net/topic/27793/test-adapter-solarlog-v1-2-x-latest/6)

solarlog v1.2.2 to stable

---

sources-dist-stable.json

I've changed the version number now. Tested the adapter with cleared timeouts.

Set Nuki v. 1.1.5 to stable

---

sources-dist.json

[Forum Test](https://forum.iobroker.net/topic/26558/test-adapter-solarviewdatareader-v0-0-x)
[Forum Entwicklung](https://forum.iobroker.net/topic/23359/neuer-adapter-solarviewdatareader)

solarviewdatareader added to latest

---

sources-dist-stable.json

Revert https://github.com/ioBroker/ioBroker.repositories/commit/4f1d8b04fd09b588c8caecd6414d5722ffaefe83#diff-5b48e2b249bd3bd9a3f3827fccaabffeL558

revert iot stable version

---

sources-dist-stable.json

https://github.com/Zefau/ioBroker.hue-extended/issues/47

Update hue-extended in stable

---

sources-dist-stable.json

please add squeezeboxrpc v1.0.0 to stable repository

add squeezeboxrpc to stable

---

sources-dist-stable.json

please add openligadb v1.0.0 to stable repository

add openligadb to stable

---

sources-dist.json

https://forum.iobroker.net/topic/31485/test-adapter-windows-control-v0-1-x-github

windows-control added

---

sources-dist.json

add rssfeed to latest

---

sources-dist.json

Sorry but I dont understood the issues from the adapter checker.

add ioBroker.alarm sources-dist.json

---

sources-dist-stable.json

(holomekc) Improved error handling
(holomekc) Added open doors and windows feature
(holomekc) functions and rooms are only added for new channels
(holomekc) increase timeout for requests which expect to contain more data

Bosch Smart Home Bridge Adapter stable 0.1.7

---

sources-dist-stable.json

Fix issues with login and add units to ioBroker state values

Update sunny portal version

---

sources-dist-stable.json

tested and confirmed in live environment by 5 users, please merge before repo update

[Important] Bugfix corona loss of service now

---

sources-dist-stable.json

virtualpowermeter update 1.2.1

---

sources-dist-stable.json

improve detection of empty-changes in objects to avoid spamming traffic

update iogo to 0.5.9

---

sources-dist-stable.json

- fixed bug in scenario handling which was introduced in 0.1.8
- minor improvements
https://github.com/holomekc/ioBroker.bshb/pull/26

Bosch Smart Home Bridge Adapter stable 0.1.9

---

sources-dist-stable.json

Updated vis-inventwo stable version to 1.3.3

Updated vis-inventwo stable version to 1.3.3

---

sources-dist-stable.json

moma 1.2.6

---

sources-dist-stable.json

https://github.com/instalator/ioBroker.exchangerates/issues/4

Added exchangerates

---

sources-dist-stable.json

@Apollon77 Denke daran, dass der Info Adapter bei der Installation integriert ist und da die Version auch angepasst werden muss. (hast du mir mal gesagt)

Add Info 1.7.2 to stable

---

README.md

prevent error:
[E802] No topics found in the repository. Please go to "https://github.com/xxx/ioBroker.xxx" and press Manage topics

add need topics

---

sources-dist-stable.json

https://github.com/ioBroker/ioBroker.repositories/pull/723

added fixed mclighting

---

sources-dist-stable.json

* Forum Thread: https://forum.iobroker.net/topic/31485/test-adapter-windows-control-v0-1-x-github
* All successfully tested.
* All requirements fulfilled

Add windows-control to stable

---

sources-dist-stable.json

Ring Adapter Version 1.1.3

---

sources-dist-stable.json

Update sources-dist-stable.json add alarm

---

sources-dist-stable.json

fixes: https://github.com/AlCalzone/ioBroker.g-homa/issues/34

Update G-Homa to 0.5.2

---

sources-dist-stable.json

https://forum.iobroker.net/topic/33177/test-adapter-ecovacs-deebot-v0-6-x-latest
Thank you in advance

Added ecovacs-deebot to sources-dist-stable.json

---

sources-dist-stable.json

- closes https://github.com/foxriver76/ioBroker.denon/issues/78

Bump denon

---

sources-dist-stable.json

- closes https://github.com/foxriver76/ioBroker.sonnen/issues/34

Bump Sonnen

---

sources-dist.json

Added vis-icontwo to latest

---

sources-dist.json

Adapter does not work work anymore

remove Primelab

---

sources-dist-stable.json
sources-dist.json

Selfmade Door Intercom for ioBroker

add doorio

---

sources-dist-stable.json

Updated vis-inventwo to 1.3.8
Added vis-icontwo to stable (v0.1.11)

Added vis-icontwo to stable &  updated vis-inventwo

---

sources-dist-stable.json

Updated vis.icontwo to 0.2.0

---

sources-dist-stable.json

Please add smartgarden adapter to stable repo. Thanks

add smartgarden to stable

---

sources-dist-stable.json

Some code needs still to be reworked, but we need to bring the adapter back functional first!
I've already fixed some basic stuff, but ofc. more needs to be done

Updated latest innogy-smarthome lib to 0.3.6

---

sources-dist.json

Original adapter request: https://github.com/ioBroker/AdapterRequests/issues/339
Forum thread: https://forum.iobroker.net/topic/33855/test-adapter-melcloud-v1-0-x-github

Add iobroker.melcloud to latest

---

sources-dist-stable.json

Forum thread with positive feedback: https://forum.iobroker.net/topic/33855/test-adapter-melcloud-v1-0-x-github-latest

Add melcloud v1.0.6 to sources-dist-stable.json

---

sources-dist-stable.json

see for information: [forum](https://forum.iobroker.net/topic/31787/test-adapter-fb-checkpresence-v1-0-x)

Updated fb-checkpresence to 1.0.4

---

sources-dist-stable.json

Update lgtv version number cause of npm update issue.

Update lgtv version number

---

sources-dist-stable.json

https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/81
Thanks :)

Bump ecovacs-deebot to 1.0.3

---

sources-dist-stable.json

see [forum](https://forum.iobroker.net/topic/32967/test-adapter-solarviewdatareader-v0-2-x)

add solarviewdatareader to stable

---

sources-dist-stable.json

Update Adapter to stable version 0.3.0

Update swiss-weather-api to stable version 0.3.0

---

sources-dist-stable.json

- closes #https://github.com/ioBroker/ioBroker.hm-rpc/issues/265

bump hm-rpc stable

---

sources-dist-stable.json

https://github.com/Zefau/ioBroker.nuki-extended/issues/82

Nuki-Extended v2.3.0 to stable

---

sources-dist.json

added vis-material-advanced to latest

---

sources-dist-stable.json
sources-dist.json

Changing Icon from PNG to SVG also.

 Updating MieleCloudService to v2.0.0 in stable repo

---

sources-dist-stable.json

 Add kostal-piko-ba to stable

---

sources-dist-stable.json
sources-dist.json

Adapter zur Lüftungssteuerung der zentralen Lüftungsanlage "Ventcube" (Schwörerhaus KG)

Add schwoerer-ventcube adapter

---

sources-dist-stable.json

minor update for Corona-Statistics

---

sources-dist-stable.json

Please add mydlink to stable repository. Would be the first version.
It is in latest for a while now and seems to work good for the few users it has. :-)

Mydlink v1.1.7

---

sources-dist-stable.json

new npm version  https://github.com/ioBroker/ioBroker.repositories/pull/952#issuecomment-716213202

Update Viessmann (formally)

---

sources-dist-stable.json

https://github.com/iobroker-community-adapters/ioBroker.hue/issues/144

bump stable hm-rpc, hue

---

sources-dist-stable.json
sources-dist.json

Hi there,
yould you please add my Adapter to the stable repository
see forum https://forum.iobroker.net/topic/37235/vis-material-advanced-widgets/25
regards
E

vis-material-advanced stable

---

sources-dist-stable.json
sources-dist.json

kecontact was enhanced to change depending on photovoltaics with several possibilities of adjustements.

updated kecontact to v1.0.1

---

sources-dist-stable.json

https://github.com/foxriver76/ioBroker.bring/issues/56

bump bring

---

sources-dist-stable.json

Please add smartcontrol 1.0.0 to stable repository, it is well tested.
* Github: https://github.com/Mic-M/ioBroker.smartcontrol
* Latest forum thread: https://forum.iobroker.net/topic/36750/
Thanks

Add smartcontrol 1.0.0 to stable repository

---

sources-dist-stable.json

Updated ioBroker.netatmo to latest version (requested by Netatmo)

Updated ioBroker.netatmo to latest version

---

sources-dist-stable.json

Test/discussions/results see: https://forum.iobroker.net/topic/34961/test-adapter-nanoleaf-lightpanels-v1-0-x-github-latest

Update nanoleaf-lightpanels to stable 1.0.6

---

sources-dist-stable.json

new stable version  with some minor design changes

new version for stable

---

sources-dist-stable.json

Forum: https://forum.iobroker.net/topic/33271/test-adapter-minuvis-v0-0-x
No Discovery necessary, only visualization
Thank you

put ioBroker.minuvis V1.0.0 in stable

---

sources-dist.json

GitHub: https://github.com/withstu/ioBroker.heos
Forum: https://forum.iobroker.net/topic/10420/vorlage-denon-heos-script
Please review and add to Latest.

add heos to latest

---

README.md
sources-dist.json

Started to learn how adapter works and I would like to implement
https://github.com/ioBroker/AdapterRequests/issues/226
as a first "training".

add adapter followthesun to latest repository

---

sources-dist-stable.json

Test Forum: see [here](https://forum.iobroker.net/topic/37959/test-adapter-fb-checkpresence-v1-1-x)

update fb-checkpresence to 1.1.0

---

sources-dist-stable.json

GitHub: https://github.com/withstu/ioBroker.heos
Forum: https://forum.iobroker.net/topic/10420/vorlage-denon-heos-script

add heos to stable

---

sources-dist-stable.json
sources-dist.json

Hi,
this will not run but also not without any modifications. It will fail with this message
>  1) Test Repository
>       Test all Packages in latest are loadable via http and name is equal to io-package.json are :
>     Error: the string "Error occurred, see console output" was thrown, throw an Error :)
>      at runMicrotasks (<anonymous>)
>      at processTicksAndRejections (internal/process/task_queues.js:97:5)
It will however pass this step with only my adapter in the list...
Greetings

Added adapter frontier_silicon

---

sources-dist-stable.json

https://github.com/foxriver76/ioBroker.sonnen/issues/53

bump sonnen stable

---

sources-dist-stable.json

Forum: https://forum.iobroker.net/topic/37915/test-adapter-device-reminder-v0-x

Please add device-reminder V 0.5.4 to stable

---

sources-dist-stable.json

The tester thread can be found here:
[https://forum.iobroker.net/topic/36474/test-adapter-growatt-v0-0-14](https://forum.iobroker.net/topic/36474/test-adapter-growatt-v0-0-14)

Add Growatt Adapter 0.0.14 to stable

---

sources-dist.json

add Todoist2 Version 0.7.1 to latest

---

sources-dist.json

Needed for https://github.com/ioBroker/ioBroker.repositories/pull/1031

Change type from followthesun to "geoposition"

---

sources-dist.json

Dies ist ein Adapter um die Daten, die die Tempest Wetterstation von Weatherflow per UDP im lokalen Netzwerk sendet auszuwerten.
Der Thread zum Adapter ist https://forum.iobroker.net/topic/35007/adapter-weatherflow_udp.
Danke für einen Review.

Added Adapter "weatherflow_udp"

---

sources-dist-stable.json

bump kostal-piko-ba to 1.1.5 for stable repo

bump kostal-piko-ba to 1.1.5 for stable repo

---

sources-dist-stable.json

Group Calculations only after InitialFinished

Update virtualpowermeter 1.2.2

---

sources-dist-stable.json

Confirmed stable version of stiebel-isg adapter, due to forum-test thread: https://forum.iobroker.net/topic/39609/test-adapter-stiebel-isg-v1-6-x

new stable version of stiebel-isg

---

sources-dist-stable.json

After something about 120 active working people with this adapter I will publish it into a stable build.

Added adapter go-e in Version 1 to stable

---

sources-dist-stable.json

bugfix, feedback see 
https://github.com/iobroker-community-adapters/ioBroker.solarlog/issues/37

solarlog v2.0.1

---

sources-dist-stable.json

Moved to iobroker-community-adapters repro

Ring Adapter

---

sources-dist-stable.json

Changes:
https://github.com/holomekc/ioBroker.bshb/pull/32
https://github.com/holomekc/ioBroker.bshb/pull/35
some automatic prs from github due to lib updates
It is some time ago when I created a pr. If I forget something please let me know. 
I hope you have a great day.

Bosch Smart Home Bridge Adapter stable 0.1.12

---

sources-dist-stable.json

Solve issue: https://github.com/withstu/ioBroker.heos/issues/36

bump heos stable version

---

sources-dist-stable.json

update vis-icontwo to 0.40.0

---

sources-dist-stable.json

Update to new bosch api-version 2.1. Add control of alarm state supporting profiles as well.
https://github.com/holomekc/ioBroker.bshb/commit/8b9a5ad84af591e038a35feae7c5b32cfccc64f6

Bosch Smart Home Bridge Adapter stable 0.1.13

---

sources-dist-stable.json

Shelly Adapter

---

sources-dist.json

https://forum.iobroker.net/topic/40984/test-adapter-epson-ecotank-et-2750-v0-0-x

Add epson_ecotank_et_2750

---

sources-dist.json

Add alias-manager

---

sources-dist.json

I've created an Adapter to control the Twinkly Lights. 
Repo: https://github.com/patrickbs96/ioBroker.twinkly
Forum: https://forum.iobroker.net/topic/39632/new-adapter-twinkly

Add Twinkly Adapter into latest

---

sources-dist.json

This is a new pull request. On the old one was no activity over one month

Pls add new Adapter for LG ESS Home Inverter

---

sources-dist-stable.json

please update smartgarden v1.0.3 to stable
Thanks

smartgarden v1.0.3 to stable

---

sources-dist-stable.json

Shelly Adapter Version 4.0.6

---

sources-dist-stable.json

- OctoPrint 1.0.8
- LaMetric 1.2.0
- TrashSchedule 1.1.1
- YouTube 1.0.3
- Luftdaten 1.0.2

Several adapter updates

---

sources-dist-stable.json

Forum:
https://forum.iobroker.net/topic/40985/ecovacs-deebot-adapter-v1-0-13-beta-latest
Thank you

Ecovacs Deebot adapter stable version 1.1.0

---

sources-dist-stable.json

Closes dkleber89/ioBroker.beckhoff#41

Update Beckhoff Adapter to 1.4.0

---

sources-dist.json

I created a new adapter that allows the user to create time scheduled switching actions using a vis widget.
Adapter repo: https://github.com/walli545/ioBroker.time-switch
Forum thread: https://forum.iobroker.net/topic/31479/test-adapter-time-switch-v1-0-x-github-latest/
Adapter request: https://github.com/ioBroker/AdapterRequests/issues/219

Add time-switch to latest

---

sources-dist-stable.json
sources-dist.json

* Bumped Miele CloudService to Version 2.0.3 in stable, Miele CloudService contains some minor bugfixes
* Added new Adapter dysonAirPurifier to latest, complete new development.

Bumped Miele CloudService to Version 2.0.3 in stable and added dysonAirPurifier to latest

---

sources-dist-stable.json

* (Stübi) Add universal IR controller (type 52)
* (Stübi) Send SMS if you are using a sim card

Lupusec Version 1.3.2

---

sources-dist-stable.json
sources-dist.json

Hallo,
ich habe einen Adapter für ein Bewässerungsgateway implementiert und möchte diesen gerne offiziell im ioBroker aufnehmen.
Es gibt hier auch bereits eine [Adapteranfrage ](https://github.com/ioBroker/AdapterRequests/issues/400)und einen entsprechenden [Testthread](https://forum.iobroker.net/topic/37467/test-adapter-linktap-v-0-0-x).
Vielen Dank vorab.

Added new adapter "linktap"

---

sources-dist-stable.json
sources-dist.json

Hello,
please add iobroker.haassohn version 1.0.3 to the stable repository.
Best regards

Add ioBroker.haassohn v1.0.3 to stable

---

sources-dist-stable.json

please update smartgarden v1.0.4 to stable
- necessary adjustments due to js-controller v3.2 (warning _"has no existing object, this might lead to an error in future versions"_)
- meanwhile unnecessary state/object removed 
Thanks
jpgorganizer

smartgarden v1.0.4 to stable

---

sources-dist.json

add valuetrackerovertime to latest

add valuetrackerovertime to latest

---

sources-dist-stable.json

starline
kodi
mercury
mclighting
mpd
foobar2000
lgtv-rs
sanext
haier
exchangerates
omnicomm-lls
synology
benq
mikrotik

Update adpater instalator

---

sources-dist-stable.json

fix mercedesme login

---

sources-dist-stable.json

fix again missing content type

update mercedesme refreshtoken

---

sources-dist.json

Hi,
I've renamed the adapter diashow because the correct name should be slideshow.
Ralf

Rename Adapter diashow to slideshow

---

sources-dist-stable.json
sources-dist.json

field tested by divera247 power user group (facebook)

New Divera247 stable version

---

sources-dist-stable.json

https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/129
Thanks :)

Update stable version of ecovacs-deebot to 1.1.1

---

sources-dist-stable.json

update to 1.6.0 for stable Version

new version material-advanced adapter

---

sources-dist-stable.json

Stable version of Lupusec and Shelly adapter

Stable version of Lupusec and Shelly

---

sources-dist-stable.json

Contact-ID Version 1.0.2

---

sources-dist-stable.json

oppoplayer 0.2.4

---

sources-dist-stable.json

api changed from http to https

update worx to 1.3.0

---

sources-dist.json

Hi, I want to add my adapter googleauth to the latest repository.

ioBroker.googleauth added to latest

---

sources-dist-stable.json

https://forum.iobroker.net/topic/40984/test-adapter-epson-ecotank-et-2750-v0-0-x

Add ioBroker.epson_ecotank_et_2750 with v0.0.4

---

sources-dist-stable.json

https://forum.iobroker.net/topic/40995/test-adapter-traccar-v0-0-x

Add ioBroker.traccar with v0.0.7

---

sources-dist-stable.json

Hi Apollon,
please push version of adapter fahrplan to 1.0.7 in stable.
Ralf

Update fahrplan to 1.0.7

---

sources-dist-stable.json

new Version 1.7.0 with window3 widget and simple temperature widget

v1.7.0 material-advanced

---

sources-dist-stable.json

Version 1.4.1 is a Bugfix release. Changes are tested and confirmed to be working.

Update ds18b20 in stable to v1.4.1

---

sources-dist-stable.json

iobroker-community-adapters as new owner

statistics 1.0.4

---

sources-dist-stable.json
sources-dist.json

updated MieleCloudService to 4.0.21
* fixed some type warnings for js-controller 3.3

updated MieleCloudService to 4.0.22

---

sources-dist-stable.json
sources-dist.json

field tested by facebook group DIVERA 24/7 Power-User

Raised version of ioBroker.divera247 to current stable version

---

sources-dist-stable.json

same as 1.0.2 but with some more minor bugs. No functional enhancements

Update go-e to 1.0.4

---

sources-dist-stable.json

Changes are tested and confirmed to be working. Also includes compatibility with js-controller >= 3.2

Bump melcloud in stable to 1.1.4

---

sources-dist-stable.json

js-controller 3.3.x compatibility, test-feedback see [Forum](https://forum.iobroker.net/topic/31425/test-adapter-solarlog-v2-0-x-latest/24)

solarlog v2.1.2

---

sources-dist-stable.json

js-controller 3.3.x compatibility, test-feedback see [Forum](https://forum.iobroker.net/topic/28712/test-adapter-luxtronik1-v0-3-x-latest-github/18?_=1621067179918)

luxtronik1 v0.3.1

---

sources-dist-stable.json

smartgarden v1.0.5 to stable

---

sources-dist-stable.json

Travis CI: i.O.
adapter-check.iobroker.in: i.O.
Forum Test: https://forum.iobroker.net/topic/44493/test-adapter-sprinkle-control-0-1-4-latest/82?_=1621622170946

add sprinklecontrol 0.1.7 to stable 

---

sources-dist-stable.json
sources-dist.json

* updated MieleCloudService to 4.2.0
* Added dysonAirPurifier 0.9.1 to stable

updated MieleCloudService to 4.2.0; Added dysonAirPurifier to stable

---

sources-dist-stable.json

problem correction with fix version of herdsman

zigbee 1.5.6

---

sources-dist-stable.json

Updated includes bugfixes, Admin 5 support, Scheduling priorities (tiers) & test-support for Node.js 16

Update schwoerer-ventcube to 1.4.1

---

sources-dist-stable.json

Fixes: https://github.com/AlCalzone/ioBroker.zwave2/issues/652

Bump zwave2 to 1.10.1

---

sources-dist-stable.json

https://github.com/AlCalzone/ioBroker.tradfri/issues/621

Bump tradfri to 2.7.3

---

sources-dist-stable.json

Bugfix to handle incorrect XML path

Update Meteoalarm to 1.2.1

---

sources-dist-stable.json

(Stübi) Add device keypad outdoor v2
(Stübi) Add log file state. Important time of Lupusec Alarm system and ioBroker have to be synchrony
(Stübi) Workaround dropdown list with admin in react mode (wrong type)

Stable Lupusec Adapter

---

sources-dist-stable.json

Add Trivum Adapter

---

sources-dist-stable.json

Changes: Updated dependencies due to security issues

Update iobroker.haassohn to v.1.0.4

---

sources-dist.json

Due to legal reasons removed, will be readded with new name soon

Remove vodafone-speedtest

---

sources-dist-stable.json

add ioBroker.tado to stable

---

sources-dist-stable.json

confirmed stable version of stiebel-isg

update stable version of stiebel-isg

---

sources-dist-stable.json

confirmed stable version of energymanager

Update version of energymanager

---

sources-dist-stable.json

confirmed stable version of energymanager

Update stable version of pi-hole

---

package.json
sources-dist-stable.json
sources-dist.json

New try - I did it like described in https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository but there are many changes in the PR.
Please give me advice what I shall do.

add bydhvs adapter

---

sources-dist-stable.json

Update of energymanager and stiebel-isg adapters due to npm error.

Update stable version of two adapters

---

sources-dist-stable.json

Go-e from Version 1.0.13 to 1.0.15 on stable

Go-e from Version 1.0.13 to 1.0.15 on stable

---

sources-dist-stable.json

fixes iobroker-community-adapters/ioBroker.ring#93
fixes iobroker-community-adapters/ioBroker.ring#6
fixes iobroker-community-adapters/ioBroker.ring#56
fixes iobroker-community-adapters/ioBroker.ring#132

upgrade ring adapter

---

sources-dist.json

Hi, 
please add my adapter for anelhut to stable. 
This adapter was tested with the developer of anel. 
All devices are working.
Br
Daniel

add anel hut to latest

---

sources-dist-stable.json
sources-dist.json

fixed issue with invalid date in timestamps

version update weatherflow_udp

---

sources-dist-stable.json
sources-dist.json

Bumped dysonAirPurifier to V0.9.2

Bumped dysonAirPurifier to V0.9.2

---

sources-dist.json

Renault ZOE Adapter using the Renault API that is active since 2019 (API V2)

Added zoe2

---

sources-dist.json

The old PR was deleted automatically because i had to reset my master branch.
https://github.com/hacki11/ioBroker.speedport/

Add speedport to latest

---

sources-dist-stable.json
sources-dist.json

Bumped dysonAirPurifier to V0.9.4

Bumped dysonAirPurifier to V0.9.4

---

sources-dist-stable.json

Systems log errors
Add vaccination data

Update coronavirus Statistics

---

sources-dist-stable.json

closes: https://github.com/AlCalzone/ioBroker.zwave2/issues/695

Bump zwave2 to 1.10.4

---

sources-dist-stable.json
sources-dist.json

0.2.0
(Smart-Gang) Changed types of state 'signal' to number and of button 'StartEcoInstantMode' to boolean.
0.1.9
(Smart-Gang) Community suggestion: The trigger data points (buttons) now have the status set to false by default.

Version update

---

sources-dist-stable.json

Bump kostal-piko-ba to 1.1.11

---

sources-dist-stable.json

- Fixed all JS-controller warnings
- Optimized code structure and system load
- Changed communication from Polling to websocket Live connection

release WLED 0.6.1 to stable

---

sources-dist.json

this adapter will replace the current iogo adapter within the next weeks/months

add new adapter iogopro

---

sources-dist-stable.json
sources-dist.json

Forum thread: https://forum.iobroker.net/topic/39632/new-adapter-twinkly
Working on the discovery function at the moment

 add Twinkly to stable

---

sources-dist-stable.json
sources-dist.json

fix vwv2 refresh
fix skoda login

Update vw-connect adapter

---

sources-dist-stable.json
sources-dist.json

Update CI testing from PR and update of dependecy version numbers

Update CI testing

---

sources-dist-stable.json

Bumped dysonAirPurifier to v1.1.0

Bumped dysonAirPurifier to v1.1.0

---

sources-dist-stable.json

update vw-connect again

---

sources-dist-stable.json

https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/171
Thanks :)

Update stable version of ecovacs-deebot to 1.2.4
