ioBroker/ioBroker.repositories

sources-dist-stable.json, sources-dist.json
Hi Bluefox,
hier mal ein Adapter, so dass man EgiGeoFence (App) auf Android fürs Geofencing nutzen kann. Basis ist der Geofency-Adapter, Tests sind ebenfalls aktiviert und das Paket ist bei NPM gepublished.
VG
Bastian
=> added egigeozone adapter

sources-dist-stable.json
Since the current stable version (0.1.0) the admin UI had a bug making it impossible to add new devices.
v0.1.2 fixes that.
I wanted to get the PR ready, but I'd wait for confirmation http://forum.iobroker.net/viewtopic.php?p=92505#p92505 before merging.
=> "emergency" fix: bump G-Homa version to 0.1.2

sources-dist-stable.json
Yesterday's gateway update changed how the connection is initialized and broke all versions prior to 0.5.5.
=> Emergency fix: bump Tradfri to 0.5.5

sources-dist-stable.json
v0.3.4 (from Github) has been in testing for a while now. I just published the package to npm.
=> Move BLE 0.3.4 to stable

sources-dist-stable.json
+ daswetter: 1.0.3
+ sbfspot: 2.2.0
+ vis-weather: 1.2.0
move ebus to stable with 0.5.0
=> new versions

lib/tools.js, package.json
to work without js-controller's outdated `npm` package
Followup to:
https://github.com/ioBroker/ioBroker.js-controller/pull/174
=> Reworked npm adapter version check

sources-dist.json
This is an adapter to poll the locations from users from Google Sharedlocations. Some users want this adapter to be in the repo.
=> added google-sharedlocations adapter

sources-dist-stable.json
- bump sonnen adapter stable version 0.0.3 --> 0.0.5
=> Update sonnen stable

sources-dist-stable.json
This version of the adapter supports all products from stall.biz that support sending a datagram. This adapter was tested by me and at least one other user with a different setup. I suppose it is stable.
=> added stable version 2.0.0 of the wiffi-wz adapter

sources-dist-stable.json, sources-dist.json
- Updated latest stable version of innogy smarthome adapter (required by the INNOGY/RWE team)
- Removed RWE SmartHome adapter as the required software is no longer available
=> Updated RWE/Innogy adapters

sources-dist-stable.json
Hasn't been out long, but it contains only incremental bugfixes over 1.5.0 which has been out for 3 weeks now. Also it should finally solve the installation problems with node-aead-crypto.
=> Push tradfri 1.5.4 to stable

sources-dist.json
Please remove the adapter from repository. Google has changed something regarding their login procedure and the workaround will take a while.
=> removed adapter google-sharedlocations, it is not working anymore

sources-dist-stable.json, sources-dist.json
updating v2 in both repos has no effect since npm is already on 2.0.1 (see https://github.com/ioBroker/ioBroker.repositories/issues/302)
=> nello: updating to v2

sources-dist.json
I have reworked the existing ioBroker.nuki adapter and optimized the code.
Furthermore, I have added the following features:
- using both Bridge API and Web API (current adapter only uses bridge API)
- support for multiple bridges
- support for discovery within admin panel
- additional states for bridges and better separation between software / hardware bridge
- retrieve the basic and advanced configuration from the lock
- retrieve all users having access to the lock
- added Web Interface to view logs
=> Add ioBroker.nuki2 to latest repository

sources-dist-stable.json
- harmony 1.2.1 stable because 1.5 was broken by logitech again
- cc: @Pmant
=> harmony stable upgrade

sources-dist-stable.json
Changes between Version 1.2.4 and 1.4.3:
1.4.3 (2019-02-21)
(BuZZy1337) Bugfix for not yet completely implemented feature
1.4.2 (2019-02-18)
(BuZZy1337) fix for recipients containing withespaces
(BuZZy1337) change loglevel of "getMe" info-messages to debug
(bluefox) fix scroll in firefox
1.4.1 (2019-01-12)
(simatec) Support for Compact mode
1.4.0 (2019-01-06)
(bluefox) Custom settings for states were added
1.3.6 (2018-12-01)
(Apollon77) fix #78
1.3.5 (2018-11-04)
(BuZZy1337) Fix a small error caused by previous commit
1.3.4 (2018-11-04)
(BuZZy1337) Ask if saved users should be wiped when password is changed.
1.3.3 (2018-11-03)
(BuZZy1337) Show warning if no password is set.
1.3.2 (2018-10-28)
(BuZZy1337) Just minor cosmetic fixes/changes
1.3.1 (2018-10-08)
(bluefox) The ability of …
=> Move Telegram Adapter 1.4.3 from latest to stable

sources-dist-stable.json
New stable Version for following adapters:
- Lupusec (almost all Lupus devices will now be supported, node 8 is required)
- Shelly (new devices supported and bugfixing)
- Pollenfilter (bugfixing and new functionality)
=> Lupusec, Pollenflug and Shelly Adapter

sources-dist.json
This adapter can discover and add devices which followed hass defined mqtt protocol.
Signed-off-by: SchumyHao <schumyhaojl@126.com>
=> Add new adapter hass-mqtt

sources-dist.json
hue-extended adapter to retrieve all information from Hue Bridge.
- Synchronize Config
- Synchronize Groups
- Synchronize Lights
- Synchronize Resources
- Synchronize Rules
- Synchronize Scenes
- Synchronize Schedules
- Synchronize Sensors 
- Trigger changes on states `on/off`, `bri` (`level`), `hue`, `sat`, `xy`, `ct`, `alert`, `effect` and `transitiontime`
- Additional triggers based on color spaces for `rgb`, `hsv`, `xyz`, `cmyk` and `hex`
- Run scene or apply `scene` on light or group
=> Add hue-extended to latest repository

sources-dist-stable.json
Updated latest innogy-smarthome lib to 0.3.3
Version 0.2.x is outdated and will not be compatible with the next update
=> Updated latest innogy-smarthome lib to 0.3.3

sources-dist.json
When I added ZWave2 with #479 I started a little experiment. The adapter is the first one to use an SVG icon. While that mostly works, it breaks in the adapter list:
The reason is that `https://raw.githubusercontent.com/AlCalzone/ioBroker.zwave2/master/admin/zwave2.svg` shows the SVG source code while `https://raw.githubusercontent.com/AlCalzone/ioBroker.zwave2/master/admin/zwave2.svg?sanitize=true` has the correct MIME type to display an image.
This PR fixes that (or rather starts another experiment to see **if the query string breaks any scripts**)
/cc @GermanBluefox @Apollon77
=> Fix ZWave2 icon url

sources-dist-stable.json
The RadioHead adapter is already in the latest repository for about two month.
The [forum post](https://forum.iobroker.net/topic/24197/aufruf-neuer-adapter-iobroker-radiohead) has unfortunately no feedback, but I'm running the adapter since several weeks now and it seams to be stable.
=> Add radiohead v1.0.2 to stable

sources-dist.json
I had accidentally specified a wrong type for the _ds18b20_ adapter in the latest repo. Sorry!
=> Fixed wrong type for ds18b20 adapter in latest

sources-dist-stable.json
New stable versions for following adapters:
* Lupusec from 1.1.8 to 1.2.0 (new devices like Nuki door opener, bugfixing)
* Ring from 1.0.4 to 1.0.5 (bugfixing for js-controller >= 2)
* Shelly 3.0.8 to 3.1.0 (new devices like dimmer, bugfixing)
all adapters are js-controller 2 ready.
=> Stable: Lupusec, Shelly, Ring

sources-dist-stable.json
Version 0.4.13 is needed for new app version 2.0.0
=> Update ioBroker.iogo version to 0.4.13

sources-dist-stable.json
Bugfix of pollen risk adapter. Without this bugfix the pollen risk adapter does not work anymore because of a DWD SSL change.  
see https://forum.iobroker.net/topic/20288/aufruf-neuer-dwd-pollenflug-adapter/129
=> Pollenflug adapter

sources-dist.json
Test-Thread:
https://forum.iobroker.net/topic/26428/test-adapter-tesla-motors-v0-1-x
Released current version is v0.2.0, also on NPM.
I still get 2 errors on https://adapter-check.iobroker.in/, but I've added Bluefox on NPM and included travis testing, so this should be fine.
=> Add tesla-motors to repositories

sources-dist-stable.json
Hi. I would add the first stable version of the adapter. There was an issue in 0.1.3 which is fixed in 0.1.4 and I did not receive any other issues.
=> Bosch Smart Home Bridge Adapter stable 0.1.4

sources-dist-stable.json
Version 2.2.0 appears to be stable.
=> Updated stable version of wiffi-wz to 2.2.0

sources-dist-stable.json
- 1.0.5 has getMessage warning on stable  with stable controller
- https://github.com/iobroker-community-adapters/ioBroker.email/issues/25
=> bump email

sources-dist-stable.json
new version is ignoring the "ts" from objects for object-hash creation, as the value in object "ts" is triggered from some adapters without changing the object in a high frequency (like spamming).
=> update iogo to 0.5.8

sources-dist.json
Initial release of this adapter for test. Although it seems to work perfectly in my installation :)
=> Added legrand-ecocompteur

sources-dist-stable.json
Here you can find the Forum thread [Test 1.0.x](https://forum.iobroker.net/topic/31787/test-adapter-fb-checkpresence-v1-0-x)
=> update fb-checkpresence to version 1.0.3 in stable repo

sources-dist-stable.json
I'm preparing the stable release for Z-Wave 2. v0.14.6 will probably be the final version before that is going to happen.
I'm raising this PR to find potential problems while the final tests are going on.
=> Add zwave2 to stable

sources-dist-stable.json
Stable Version 3.3.3
* (Stübi) - Use only version with Shelly firmware greater equal v1.7.0 . Shelly firmware less v1.7.0 will not be supported by this Shelly adapter version anymore
* (Stübi) - Add state vibration and tilt to Shelly DW
* (Stübi) - Add polltime to index_m.html  
* (Stübi) - Fix RGBW2 with FW 1.7 - Issue #161
* (Stübi) - Add state Button Type for Shelly  1, 1PM, 2, 2.5 - Issue #157
* (Stübi) - Add state Button Reverse for Shelly 1, 1PM, 2, 2.5
* (Stübi) - Add firmware update button
* (Stübi) - Fix auto firmware update
* (Stübi) - Add state external humidity to Shelly 1 / 1PM - Issue #160
* (Stübi) - Add helper library and cleanup source code
* (Stübi) - Add Shelly I3
=> Shelly Version 3.3.3

sources-dist-stable.json
Needed update in order to bring innogy adapter back functional with the new AUTH endpoint
=> Updated latest innogy-smarthome lib to 0.3.5

sources-dist-stable.json
Add logparser to stable. 
Adapter is very stable: used by many users and no issues for several weeks.
https://github.com/Mic-M/ioBroker.logparser
=> logparser to stable

sources-dist-stable.json
I constantly get an error in the adapter checker, that bluefox is missing in the owner list of the npm package though I have added the user:
=> Update stable version for klf200.

sources-dist-stable.json
* (Stübi) - Add Shelly Dimmer 2
* (Stübi) - Add states longpush and input to Shelly Dimmer 1 (MQTT)
* (Stübi) - Add states power and energy to Shelly Duo
* (Stübi) - Get power and energy by CoAP instead of http for Shelly 1 PM
* (Stübi) - Bugfixing Shelly Button 
* (Stübi) - Bugfixing Shelly 1 humidity MQTT
* (Stübi) - Fixed typo error (external temperature) / Shelly 1, 1 PM 
* (Stübi) - Fixed role for external temperature / Shelly 1, 1 PM 
* (Stübi) - Changed CoAP concept, because Shelly will change the CoAP payload in one of the future firmware versions. This makes the adjustments later easier. 
* (Stübi) - Shelly 4 Pro not supported anymore. If you need it please create an GitHub issue.
* (Stübi) - Shelly RGBW not supported anymore. If you need it please create an GitHub issue .
=> Shelly Version 3.3.4

sources-dist.json
Added an adapter for go-e for the hardware go-eCharger.
Similar to #852 / #853.
But with no error in the checking tools of ioBroker.
=> Added go-e for Hardware go-eCharger

sources-dist.json
sprinklecontrol, "type": garden
E801 und E802 waren erledigt, wurden von https://adapter-check.iobroker.in/ nicht erkannt
[E145] Keine Neuigkeiten für aktuelle Version 0.0.6 gefunden => kann ich nicht nachvollziehen (Beschreibung wurde vervollständigt und ein Fehler im calcPosTimer behoben.
Ich hoffe das jetzt alle Kriterien erfüllt sind.
Dirk Peter
=> Update sources-dist.json with sprinklecontrol

sources-dist-stable.json
Shelly did a major change in there new firmware. After updating the Shelly devices with firmware 1.8.0 or above, the ioBroker Shelly Adapter 3.x.x does not work anymore. The ioBroker Shelly Adapter 4.0.1 will work with the new Shelly firmware 1.8.0 or above.
* (Stübi) - Major Change!! If you use the CoAP protocol only Shelly devices with Firmware 1.8.x or above supported! All devices with Firmware below 1.8.x except Shelly 4Pro will not working with this release!
(@harrym67) - Changing device files
* (Stübi) - Since Firmware 1.8. the Shelly device names like shelly.0.SHBTN-1#A4CF12F454A3#2 ends with #2. It will be changed back to #1 like shelly.0.SHBTN-1#A4CF12F454A3#1.
* (@harrym67) - Add state factoryResetFromSwitch for Shelly 1, 1pm, 2, 2.5, Dimmer, Dimmer 2 and RGBW2
* (@harrym67) - …
=> Shelly Adapter / Firmware change

sources-dist-stable.json
Update stables:
* logparser 1.0.0 -> 1.0.4 -- https://github.com/Mic-M/ioBroker.logparser
* windows-control: 0.1.3 -> 0.1.5 -- https://github.com/Mic-M/ioBroker.windows-control
See: https://github.com/Mic-M/ioBroker.windows-control/issues/9
=> Update Stables: logparser and windows-control

sources-dist.json
Github: https://github.com/Mic-M/ioBroker.smartcontrol
Forum: [Threads tagged with smartcontrol](https://forum.iobroker.net/tags/smartcontrol) | [Current thread](https://forum.iobroker.net/topic/36750/test-adapter-smartcontrol-0-3-x-github-ab-12-09-20?page=1) | [Splash Page](https://forum.iobroker.net/topic/36728/smart-control-adapter-splash-page)
Please review and add to Latest. A couple of comments, since I recently initiated discussions related to i18n and documentation, which were also related to this adapter, so this adapter is kind of a "hot iron" 😄 , but now it should meet all conventions and also providing a great usability for our users ;-)
* Compact Mode successfully checked
* https://adapter-check.iobroker.in/ looks good.
* All 10 required translations are implemented via gulp …
=> Add smartcontrol to Latest

sources-dist.json
Hi,
please integrate my adapter "fahrplan" into latest branch.
Here are the informations about the new adapter:
https://github.com/gaudes/ioBroker.fahrplan
Adapter checker result has only one false-positive error:
_[E300] Not found on travis. Please setup travis_
But I'm using travis.com
I've done a alpha version test in forum already, see here:
https://forum.iobroker.net/topic/35169/test-adapter-fahrplan-v0-1-x-github-alpha-version
There is also an old adapter request here:
https://github.com/ioBroker/AdapterRequests/issues/257
Don't hesitate to contact me for further questions.
Ralf
=> Integrating adapter fahrplan

sources-dist-stable.json
(Stübi) - Add a checkbox, to optionally enable updates of objects even if they have not changed (Issue #209)
(Stübi) - Calculate temperature fahrenheit for Shelly 1PM and Plug S in MQTT mode
(Stübi) - Fixed longpush time for MQTT (Shelly 1, 1PM, 2 and 2.5)
(Stübi) - Add State for changing temperature unit for Shelly HT and DW2
(Stübi) - Delete external temperature 4 and external humidity 4 states for Shelly 1 and 1PM because they do not exist
(Stübi) - Renamed state temperature to temperatureC for Shelly 1, 1PM, 2, 2.5, Plug S
(Stübi) - Add tmperature in Celsius and Fahrenheit for Shelly HT and DW2
(Stübi) - Bugfixing. Add missing states to MQTT, which exist for CoAP (Shelly 2, 2.5)
(Stübi) - Polltime for http optimized.
(Stübi) - removed min and max values for temperature states (Issue …
=> Shelly 4.0.3

sources-dist-stable.json
* Bugfixing
* Add sentry mode
* Now you can hold the reason for the alarm in alarm_status and alarm_status till the alarm ends
=> Lupusec Adapter stable version 1.2.9

sources-dist.json
Add my new [ioBroker.canbus](https://github.com/crycode-de/ioBroker.canbus) adapter to the latest repo.
~Adapter checker complains about `tsconfig.json` files not in `.npmignore`, but they are there with wildcards.~
Adapter request: https://github.com/ioBroker/AdapterRequests/issues/441
=> Added canbus to latest

sources-dist-stable.json
Hi,
sorry for my late reply. I've fixed the issue stated in version [1.4.1](https://github.com/ioBroker/ioBroker.repositories/pull/987) and created a new version.
=> Push Nuki v 1.4.2 to stable (fixed invalid type push,pull)

sources-dist-stable.json
This to update stable to address bug fixes. Many Latest installation users did not report any bugs, nor Sentry did.
I consider this version as stable.
Thanks.
=> Stable update of smartcontrol from 1.0.0 to 1.2.1

sources-dist-stable.json
0.0.15 set as stable. In 0.0.15 only the relationships to other packages were set to the newest version.
=> 0.0.15 set as stable.

sources-dist-stable.json
It runs for 4 weeks on 2 of my machines (compact mode and normal mode).
2 users tested it: https://github.com/sebilm/ioBroker.nibeuplink/issues/12
No problems were reported in the forum: https://forum.iobroker.net/topic/40046/test-adapter-nibeuplink-v0-4-0-latest
I did not get any error messages.
=> source-list-stable: update nibeuplink to 0.4.0

sources-dist-stable.json
All three versions are tested and I consider them stable.
The brand new odl v1.1.4 is the same as the tested v1.1.3 but with an updated logo.
=> Stable updates: ds18b20 v1.2.1, odl v1.1.4, radiohead v1.1.1

sources-dist-stable.json
Hi Apollon,
please push version of adapter fahrplan to 1.0.2 in stable.
Ralf
=> Push version of fahrplan to 1.0.2 in stable

sources-dist-stable.json
Need to update as Tesla changed authentication and older version will fail.
=> Update tesla-motors in sources-dist-stable.json

sources-dist-stable.json
Hi Apollon,
please push version of adapter fahrplan to 1.0.5 in stable.
Ralf
=> Push version of fahrplan to 1.0.5

sources-dist-stable.json
1.8.11 is not that old, but it fixes a critical bug in 1.8.10 which has been out almost 3 weeks now.
Other than that - no known issues.
=> Bump zwave2 stable version

sources-dist-stable.json, sources-dist.json
We're in the process of deprecating it. New installations should use zwave2 instead.
https://github.com/ioBroker/ioBroker.zwave/pull/121
=> Remove legacy zwave adapter

sources-dist.json
Please add this widget to the latest repo. Official documentation can be found [here](https://excodibur.github.io/ioBroker.vis-3dmodel/latest/index.html).
Tests (& build) are done via Github Actions.
There seem to be false positives [E605] and [E701] from adapter-checker. Both are related to "no year found", although it is actually set.
=> Add vis-3dmodel widget

sources-dist-stable.json
Please blacklist 0.2.2 and 0.2.3 in Sentry. Thanks!
=> bump ioBroker.fuelpricemonitor from 0.2.2 to 0.2.4

sources-dist-stable.json
The version was just released, but it only makes sure that `setState` isn't called with `undefined`, avoiding warnings in JS-Controller 3.3
=> Bump Tradfri to 2.7.2

sources-dist.json
Change type of time-switch from `time-and-date` to `date-and-time`. See https://github.com/walli545/ioBroker.time-switch/issues/134.
=> Fix time-switch type

sources-dist-stable.json
Removed a lot of info warnings.
Removed outdated dependencies.
Added function as described in Change-log.
=> go-e - Updated to Version 1.0.13

.gitignore, lib/scripts.js, package-lock.json, package.json
Currently the scripts only allow to add to latest and add to stable.
This additional script allows to update stable (or add to stable if it isn't there yet).
This script is required by the dev-portal to easily update the repositories:
https://github.com/ioBroker/dev-portal/blob/fd6ad93fb253f62b848a4cd8c85ba29977fd0408/express/backend/src/apps/to-stable.ts#L27
BTW: added package-lock.json to the repo as it simplifies installing all dependncies (one can now simply use `npm ci` instead of `npm i` which is a lot faster).
=> [Not Adapter] Add script to update stable

sources-dist-stable.json
https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/148
Version 1.2.1 was released 18 days ago.
Thanks :)
=> Update stable version of ecovacs-deebot to 1.2.1

sources-dist-stable.json
[ioBroker.canbus](https://github.com/crycode-de/ioBroker.canbus) seams to be stable and working nicely with the latest js-controller and admin 5.
Forum testing thread: https://forum.iobroker.net/topic/39033/test-adapter-canbus-v1-1-x-latest/
=> Added canbus v1.2.2 to stable

sources-dist-stable.json
* (grizzelbee) Fix: [#130](https://github.com/Grizzelbee/ioBroker.dysonairpurifier/issues/130) Fixed the newly introduced bug showing wrong values for temperatures
* (grizzelbee) Upd: Pushed to version 1.0.0
* (grizzelbee) Upd: Updated dependencies
=> Bumped dysonAirPurifier to v1.0.0

sources-dist-stable.json
Please update my adapter ioBroker.fahrplan to version 1.2.0.
*This pull request was created by https://www.iobroker.dev 15f979c.*
=> Update fahrplan to 1.2.0
